
evento1 = ('fullparty' , '05/06' , 'Quiosque' , ['João' , 'Pedro' , 'Carla'])
evento2 = ('formatura' , '20/12' , 'CineLumine' , ['Luzia' , 'Dani' , 'RosiRosi'])
evento3 = ('after' , '21/012' , 'Chacará', ['Lorena' , 'Yan', 'Kris'])
print("Evento 1:")
print("Nome:", evento1[0])
print("Data:", evento1[1])
print("Local:", evento1[2])
print("Participantes:", evento1[3])

print("Evento 2:")
print("Nome:", evento2[0])
print("Data:", evento2[1])
print("Local:", evento2[2])
print("Participantes:", evento2[3])

print("Evento 3:")
print("Nome:", evento3[0])
print("Data:", evento3[1])
print("Local:", evento3[2])
print("Participantes:", evento3[3])